# vim:syntax=sh

latest="firstaftermatchword-trim"
srcurl="https://fluentbit.io/download/"
opt_match="inner-faq-b"
opt_nonmatch=""
basename="fluentbit"
extension_input="tar.gz"
comment=""
version_holder="#version#"
minor_holder="#minor#"
major_holder="#major#"
custom_url="https://fluentbit.io/releases/#major#.#minor#/fluent-bit-#version#.${extension_input}"
custom_file_prefix="${basename}-"
custom_file_postfix=".${extension_input}"
