# vim:syntax=sh
latest="bash"
srcurl="http://ftp.gnu.org/gnu/bash/"
extension_input="tar.gz"
custom_url_prefix="${srcurl}bash-"
custom_url_postfix=".${extension_input}"
custom_file_postfix=".${extension_input}"
custom_file_prefix="bash-"
sep='"'
