# vim:syntax=sh
latest="grep"
srcurl="http://ftp.gnu.org/gnu/grep/"
extension_input="tar.xz"
extension_url="${extension_url}"
custom_url_prefix="${srcurl}grep-"
custom_url_postfix=".${extension_input}"
custom_file_postfix=".${extension_input}"
custom_file_prefix="grep-"
sep='"'
