# vim:syntax=sh
latest="readline"
srcurl="https://tiswww.case.edu/php/chet/readline/rltop.html"
baseurl="http://ftp.gnu.org/gnu/readline/"
extension_input="tar.gz"
custom_url_prefix="${baseurl}readline-"
custom_url_postfix=".${extension_input}"
custom_file_postfix=".${extension_input}"
custom_file_prefix="readline-"
sep='"'
